# Start with the official OpenJDK 21 image as the base image
FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY target/your-application.jar /app/your-application.jar

CMD ["java", "-jar", "your-application.jar"]