# Start with the official OpenJDK 17 image as the base image
FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY target/your-application.jar /app/your-application.jar

CMD ["java", "-jar", "your-application.jar"]